export const AutomationSkipReason = {
  SOURCE_STATUS_CHANGED: "SOURCE_STATUS_CHANGED",
  AUTOMATION_DISABLED: "AUTOMATION_DISABLED",
  ORDER_ALREADY_IN_TARGET_STATUS: "ORDER_ALREADY_IN_TARGET_STATUS",
  TARGET_STATUS_DELETED: "TARGET_STATUS_DELETED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  STALE_STATUS_TIMESTAMP: "STALE_STATUS_TIMESTAMP",
  CONDITIONS_NOT_MATCHED: "CONDITIONS_NOT_MATCHED",
  STALE_AUTOMATION_VERSION: "STALE_AUTOMATION_VERSION",
  TIME_NOT_ELAPSED: "TIME_NOT_ELAPSED",
  DUPLICATE_EXECUTION: "DUPLICATE_EXECUTION",
} as const;

export type AutomationSkipReasonCode =
  (typeof AutomationSkipReason)[keyof typeof AutomationSkipReason];
